import {StyleSheet, Dimensions} from 'react-native';
export default StyleSheet.create({
  placeholderContainer: {
    width: '90%',
    backgroundColor: '#ffff',
    height: 200,
    borderRadius: 50,
    marginTop: 10,
    alignSelf: 'center',
  },
  placeholder: {
    height: 7,
    marginTop: 12,
    marginLeft: 15,
    borderRadius: 50,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    backgroundColor: '#eeeeee',
  },
  notifyContainer: {
    position: 'relative',
    width: '100%',
    backgroundColor: '#ffff',
    borderRadius: 30,
    marginTop: 15,
    alignSelf: 'center',
    alignContent: 'center',
    alignItems: 'center',
  },
  notifylist: {
    marginTop: 20,
    borderRadius: 90,
    height: 170,
    backgroundColor: '#ffff',
  },
  list: {
    position: 'relative',
    alignSelf: 'center',
    flex: 1,
    width: '100%',
    height: '100%',
    padding: 20,
  },
  text: {
    alignSelf: 'center',
    fontSize: 24,
    color: '#b2bec3',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    padding: 10,
  },
  headline: {
    alignSelf: 'center',
    fontSize: 24,
    color: '#b2bec3',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    position: 'absolute',
    alignContent: 'center',
    alignSelf: 'center',
    marginBottom: 260,
    marginLeft: 25,
  },

  notfound: {
    flex: 1,
    marginTop: 200,
    alignSelf: 'center',
    marginLeft: 10,
  },
  textnotfound: {
    alignSelf: 'center',
    fontSize: 24,
    color: '#b2bec3',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    marginTop: 30,
  },
});
