import {StyleSheet, Dimensions} from 'react-native';
const {width} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ecf0f1',
    height: '100%',
    width: '100%',
    position: 'absolute',
  },
  text: {
    alignSelf: 'center',
    fontSize: 24,
    color: '#b2bec3',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    padding: 10,
  },
  form: {
    backgroundColor: '#ffff',
    alignContent: 'center',
    alignSelf: 'center',
    height: 640,
    width: '90%',
    borderRadius: 20,
    paddingTop: 20,
    borderWidth: 1,
    borderColor: '#eeeeee',
    shadowColor: '#eeeeee',
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  input: {
    height: '7%',
    width: '90%',
    alignContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#34495e',
    marginBottom: 20,
    borderRadius: 20,
    padding: 10,
    borderColor: '#34495e',
    borderWidth: 1,
    color: '#ffff',
  },

  drobDown: {
    width: 200,
    alignContent: 'center',
    alignSelf: 'center',
    borderRadius: 20,
    padding: 10,
    borderColor: '#34495e',
    borderWidth: 1,
    color: '#34495e',
  },

  textAreaContainer: {
    height: 150,
    width: '90%',
    alignContent: 'center',
    alignSelf: 'center',
    borderRadius: 20,
    borderColor: '#34495e',
    borderWidth: 1,
    padding: 10,
  },
  textArea: {
    height: 130,
    width: '100%',
    alignContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#34495e',
    marginBottom: 20,
    borderRadius: 20,
    padding: 10,
    color: '#ffff',
    padding: 20,
  },
  logoContainer: {
    alignContent: 'center',
    alignSelf: 'center',
  },
  logo: {
    width: 200,
    height: 100,
    marginBottom: 20,
    borderRadius: 20,
    alignContent: 'center',
    alignSelf: 'center',
  },
});
