import {StyleSheet, Dimensions, Platform} from 'react-native';
const {width} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    height: '100%',
    width: '100%',
  },
  slider: {
    flex: 1,
    backgroundColor: '#fff',
  },
  placeholderContainer: {
    width: '80%',
    backgroundColor: '#ffff',
    height: 150,
    borderRadius: 50,
    alignContent: 'center',
    alignItems: 'center',
    marginLeft: 40,
    marginTop: 20,
  },
  placeholder: {
    width: '90%',
    height: '60%',
    marginTop: 12,
    marginLeft: 15,
    borderRadius: 50,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    backgroundColor: '#eeeeee',
  },
  placeholdertitle: {
    height: 7,
    marginBottom: 40,
    marginLeft: 25,
    borderRadius: 50,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    backgroundColor: '#eeeeee',
  },

  imageContainer: {
    padding: 20,
  },
  ImagePreview: {
    width: '100%',
    height: 190,
    borderRadius: 200,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 15,
    borderTopRightRadius: 30,
    borderTopLeftRadius: 15,
    overflow: 'hidden',
    resizeMode: 'cover',
    shadowColor: '#0000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  txtgallery: {
    color: 'grey',
    fontSize: 20,
    fontStyle: 'normal',
    alignSelf: 'center',
    padding: 5,
    marginRight: 20,
  },
  headeingcontainer: {},
  txtarea: {
    alignSelf: 'center',
    width: '90%',
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: '#000',
    padding: 10,
    borderColor: '#000',
    borderStyle: 'solid',
  },
  txtareacntain: {
    alignSelf: 'center',
    fontSize: 15,
    alignSelf: 'center',
    fontStyle: 'normal',
  },
  headeing: {
    color: 'grey',
    fontSize: 10,
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
    marginLeft: 20,
    fontStyle: 'normal',
  },
  headeing2: {
    color: 'grey',
    fontSize: 13,
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
    fontStyle: 'normal',
  },
  author: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    marginLeft: 20,
    padding: 10,
  },
  authorImg: {
    width: '10%',
    height: 36,
    borderRadius: 200,
    marginRight: 5,
  },
  tags: {
    flexDirection: 'row',
    marginTop: 20,
    marginLeft: 30,
  },
  tagrx: {
    alignSelf: 'center',
    fontSize: 18,
    alignSelf: 'center',
    fontStyle: 'normal',
    marginRight: 20,
  },
  cattxt: {
    alignSelf: 'center',
    fontSize: 18,
    alignSelf: 'center',
    fontStyle: 'normal',
    marginLeft: 20,
  },
  cat: {
    flexDirection: 'row',
    marginTop: 20,
  },
  footer: {
    padding: 20,
  },
  notfound: {
    flex: 1,
    marginTop: 200,
    alignSelf: 'center',
    marginLeft: 10,
  },
  textnotfound: {
    alignSelf: 'center',
    fontSize: 24,
    color: '#b2bec3',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    marginTop: 30,
  },
  social: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignContent: 'center',
    alignItems: 'center',
    marginLeft: 120,
    padding: 0,
  },
});
